### ISSUE TITLE
Unable to download pre-trained weight

### ISSUE THREAD

**Issue by VONWEI13** [yny0506/Massive-Videos-Moment-Retrieval#1]
When tring to clik the link and download the pre-trained weight of RMMN, it would appear 'milabfile.snu.ac.kr didn't sent any data', which seems unable for us to download. Would it be better to upload the pre-trained weight to the public website such as Google Drive for further communication and development of this research?

**Comment by botPuneet** [comment]
HEY I KNOW THE SOLUTION CAN I PERFORM PLS

**Comment by VONWEI13** [comment]
> HEY I KNOW THE SOLUTION CAN I PERFORM PLS

Sure, I would like to know.

**Comment by yny0506** [comment]
We have checked the download link and found that our download server has been down.
We changed our link to a Google Drive link; thus, now you can connect to our pre-trained weights link.
Thanks for your interest in our paper.

**Comment by VONWEI13** [comment]
Thanks, I am able to download the pre-trained weights now.
